R/sits_cluster.R, vignettes/sits.Rmd
- Conclusion of clustering section
Others modifications:
- Bug fix in `sits_cluster_validity()`
=> Vignette update

.travis.yml, R/sits_raster.R, vignettes/sits.Rmd
The function was returning non binded raster objects.
=> Fix `sits_classify_raster`

R/sits_machine_learning.R
added normalization layer to improve gradient propagation, allowing deeper networks
=> added normalization layer

R/sits_machine_learning.R, R/sits_tibble_functions.R, src/normalize_data.cpp
Update `.sits_normalize()` and `.sits_normalization_param()` to comply the normalization procedure;
Fix `sits_qda()` parameter.
=> Fix `normalize_data()` function;

DESCRIPTION, tests/testthat/test-ml.R
=> Updating Jenkins and CI server

R/sits_coverage.R
A bug in sits_coverage prevented that sits_classification works properly.
=> Bug fix in sits_coverage

DESCRIPTION
WTSS dependence points now to github: e-sensing/wtss
=> Change WTSS dependence

R/sits_stac.R
- Change `sapply` to `map_chr` in `sits_stac.R`
=> Change 'sapply' to 'map_chr' in 'sits_stac.R'

R/sits_stac.R
- Changing the name of the bands to upper case
=> Changing to upper bands name

R/sits_config.R, R/sits_stac.R, inst/extdata/config.yml
- add limit number in stac_search
- update config.yml
=> Add limit items parameter in STAC function

R/sits_bdc.R
- Fix token addition bug only on first tile images
=> Fix token bug in sits_bdc.R

R/sits_raster_api.R, inst/extdata/config.yml
- fix bug terra filetype
- fix terra id time series bug
=> Fix terra bugs

README.md, inst/extdata/config.yml
- Add BDC cloud bands in config 
- Update README
=> Add BDC cloud bands in config 

R/sits_stac.R, inst/extdata/config.yml
- Error in select all bands from sentinel,
e.g.
```r
sentinel_cube <- sits::sits_cube(
source = "BDC",
name = "sentinel_mt_cube",
collection = "S2_10_16D_STK-1",
start_date = "2018-09-01",
end_date = "2019-08-01"
)
```
=> Hotfix sentinel

R/sits_cube.R
=> Fix duplicated dates

R/sits_accuracy.R, R/sits_get_data.R, tests/testthat/test-data.R, tests/testthat/test-roi.R
=> Fix label column being saved as factors

R/sits_get_data.R, R/sits_raster_data.R, R/zzz.R, man/sits_get_data.Rd
=> fix future bug

R/sits_raster_api.R, R/sits_smooth_aux_functions.R
=> fix smoothing result being not saved in user informed directory

R/sits_som.R
Fix the parameter "rlen" in sits_som_map() function, and add the parameter mode" provided by kohonen package to define the type of learning algorithm.
=> Fix the parameter rlen in sits_som_map() function

DESCRIPTION
=> Define new requirement of terra package version

R/sits_raster_sub_image.R
=> Fix selection of intersecting tiles

R/sits_config.R, R/sits_deafrica.R, R/sits_sentinel.R, R/sits_stac.R
Support BDC "LANDSAT-MOZ_30_1M_STK-1" cube.
=> Config fix bug

DESCRIPTION, NEWS.md, README.md, inst/extdata/config.yml
=> Bug fixes in BDC MODIS cube

DESCRIPTION
=> Fixes keras version

R/sits_get_data.R, R/sits_raster_data.R, inst/extdata/config.yml, man/dot-sits_get_data_from_wtss.Rd, man/sits_get_data.Rd
- support to interpolate time series (add `impute_fn` parameter)
- fix bugs in bands name
=> Update WTSS sits_get_data function

R/sits_source_api.R
=> add `.source_bands_resampling()` function

R/sits_source_api_wtss.R, inst/extdata/config.yml
=> add point check on wtss access test

R/sits_TempCNN.R, R/sits_validate.R, man/sits_LightTAE.Rd, man/sits_kfold_validate.Rd
Closes #649 
Fix #650 
update documentation
=> Implement parallelization in `sits_kfold_validate()` and bug fix `sits_TempCNN()`

R/sits_active_learning.R, man/sits_suggest_samples.Rd
Distance computation updated
Typo fixed
=> Active learning

R/sits_resnet.R, man/sits_resnet.Rd
- Parameter checks added to sits_resnet. 
- Duplicated entries removed from documentation.
=> Parameter checks added to sits_resnet

R/sits_view.R
=> fix sits_view plot

.drone.yml, R/sits_get_data.R, R/sits_space_time_operations.R
=> Update Drone image

R/api_accuracy.R
=> Fix `sits_accuracy()` bug 

R/api_apply.R, R/api_conf.R, R/api_cube.R, R/api_source.R, R/api_space_time_operations.R, R/api_tile.R
=> Revert "Adjust data type and properties to new computed indexes in `sits_apply()`"
